export type Country = {
    label: string;
    value: string;
    key: string;
};
export const countries: Country[] = [
    { label: "Country", value: "", key: "" },
    { label: "Afghanistan", value: "AF", key: "AF" },
    { label: "Åland Islands", value: "AX", key: "AX" },
    { label: "Albania", value: "AL", key: "AL" },
    { label: "Algeria", value: "DZ", key: "DZ" },
    { label: "American Samoa", value: "AS", key: "AS" },
    { label: "Andorra", value: "AD", key: "AD" },
    { label: "Angola", value: "AO", key: "AO" },
    { label: "Anguilla", value: "AI", key: "AI" },
    { label: "Antarctica", value: "AQ", key: "AQ" },
    { label: "Antigua & Barbuda", value: "AG", key: "AG" },
    { label: "Argentina", value: "AR", key: "AR" },
    { label: "Armenia", value: "AM", key: "AM" },
    { label: "Aruba", value: "AW", key: "AW" },
    { label: "Australia", value: "AU", key: "AU" },
    { label: "Austria", value: "AT", key: "AT" },
    { label: "Azerbaijan", value: "AZ", key: "AZ" },
    { label: "Bahamas", value: "BS", key: "BS" },
    { label: "Bahrain", value: "BH", key: "BH" },
    { label: "Bangladesh", value: "BD", key: "BD" },
    { label: "Barbados", value: "BB", key: "BB" },
    { label: "Belarus", value: "BY", key: "BY" },
    { label: "Belgium", value: "BE", key: "BE" },
    { label: "Belize", value: "BZ", key: "BZ" },
    { label: "Benin", value: "BJ", key: "BJ" },
    { label: "Bermuda", value: "BM", key: "BM" },
    { label: "Bhutan", value: "BT", key: "BT" },
    { label: "Bolivia", value: "BO", key: "BO" },
    { label: "Caribbean Netherlands", value: "BQ", key: "BQ" },
    { label: "Bosnia & Herzegovina", value: "BA", key: "BA" },
    { label: "Botswana", value: "BW", key: "BW" },
    { label: "Bouvet Island", value: "BV", key: "BV" },
    { label: "Brazil", value: "BR", key: "BR" },
    { label: "British Indian Ocean Territory", value: "IO", key: "IO" },
    { label: "Brunei", value: "BN", key: "BN" },
    { label: "Bulgaria", value: "BG", key: "BG" },
    { label: "Burkina Faso", value: "BF", key: "BF" },
    { label: "Burundi", value: "BI", key: "BI" },
    { label: "Cambodia", value: "KH", key: "KH" },
    { label: "Cameroon", value: "CM", key: "CM" },
    { label: "Canada", value: "CA", key: "CA" },
    { label: "Cape Verde", value: "CV", key: "CV" },
    { label: "Cayman Islands", value: "KY", key: "KY" },
    { label: "Central African Republic", value: "CF", key: "CF" },
    { label: "Chad", value: "TD", key: "TD" },
    { label: "Chile", value: "CL", key: "CL" },
    { label: "China", value: "CN", key: "CN" },
    { label: "Christmas Island", value: "CX", key: "CX" },
    { label: "Cocos (Keeling) Islands", value: "CC", key: "CC" },
    { label: "Colombia", value: "CO", key: "CO" },
    { label: "Comoros", value: "KM", key: "KM" },
    { label: "Congo - Brazzaville", value: "CG", key: "CG" },
    { label: "Congo - Kinshasa", value: "CD", key: "CD" },
    { label: "Cook Islands", value: "CK", key: "CK" },
    { label: "Costa Rica", value: "CR", key: "CR" },
    { label: "Côte d’Ivoire", value: "CI", key: "CI" },
    { label: "Croatia", value: "HR", key: "HR" },
    { label: "Cuba", value: "CU", key: "CU" },
    { label: "Curaçao", value: "CW", key: "CW" },
    { label: "Cyprus", value: "CY", key: "CY" },
    { label: "Czechia", value: "CZ", key: "CZ" },
    { label: "Denmark", value: "DK", key: "DK" },
    { label: "Djibouti", value: "DJ", key: "DJ" },
    { label: "Dominica", value: "DM", key: "DM" },
    { label: "Dominican Republic", value: "DO", key: "DO" },
    { label: "Ecuador", value: "EC", key: "EC" },
    { label: "Egypt", value: "EG", key: "EG" },
    { label: "El Salvador", value: "SV", key: "SV" },
    { label: "Equatorial Guinea", value: "GQ", key: "GQ" },
    { label: "Eritrea", value: "ER", key: "ER" },
    { label: "Estonia", value: "EE", key: "EE" },
    { label: "Ethiopia", value: "ET", key: "ET" },
    { label: "Falkland Islands (Islas Malvinas)", value: "FK", key: "FK" },
    { label: "Faroe Islands", value: "FO", key: "FO" },
    { label: "Fiji", value: "FJ", key: "FJ" },
    { label: "Finland", value: "FI", key: "FI" },
    { label: "France", value: "FR", key: "FR" },
    { label: "French Guiana", value: "GF", key: "GF" },
    { label: "French Polynesia", value: "PF", key: "PF" },
    { label: "French Southern Territories", value: "TF", key: "TF" },
    { label: "Gabon", value: "GA", key: "GA" },
    { label: "Gambia", value: "GM", key: "GM" },
    { label: "Georgia", value: "GE", key: "GE" },
    { label: "Germany", value: "DE", key: "DE" },
    { label: "Ghana", value: "GH", key: "GH" },
    { label: "Gibraltar", value: "GI", key: "GI" },
    { label: "Greece", value: "GR", key: "GR" },
    { label: "Greenland", value: "GL", key: "GL" },
    { label: "Grenada", value: "GD", key: "GD" },
    { label: "Guadeloupe", value: "GP", key: "GP" },
    { label: "Guam", value: "GU", key: "GU" },
    { label: "Guatemala", value: "GT", key: "GT" },
    { label: "Guernsey", value: "GG", key: "GG" },
    { label: "Guinea", value: "GN", key: "GN" },
    { label: "Guinea-Bissau", value: "GW", key: "GW" },
    { label: "Guyana", value: "GY", key: "GY" },
    { label: "Haiti", value: "HT", key: "HT" },
    { label: "Heard & McDonald Islands", value: "HM", key: "HM" },
    { label: "Vatican City", value: "VA", key: "VA" },
    { label: "Honduras", value: "HN", key: "HN" },
    { label: "Hong Kong", value: "HK", key: "HK" },
    { label: "Hungary", value: "HU", key: "HU" },
    { label: "Iceland", value: "IS", key: "IS" },
    { label: "India", value: "IN", key: "IN" },
    { label: "Indonesia", value: "ID", key: "ID" },
    { label: "Iran", value: "IR", key: "IR" },
    { label: "Iraq", value: "IQ", key: "IQ" },
    { label: "Ireland", value: "IE", key: "IE" },
    { label: "Isle of Man", value: "IM", key: "IM" },
    { label: "Israel", value: "IL", key: "IL" },
    { label: "Italy", value: "IT", key: "IT" },
    { label: "Jamaica", value: "JM", key: "JM" },
    { label: "Japan", value: "JP", key: "JP" },
    { label: "Jersey", value: "JE", key: "JE" },
    { label: "Jordan", value: "JO", key: "JO" },
    { label: "Kazakhstan", value: "KZ", key: "KZ" },
    { label: "Kenya", value: "KE", key: "KE" },
    { label: "Kiribati", value: "KI", key: "KI" },
    { label: "North Korea", value: "KP", key: "KP" },
    { label: "South Korea", value: "KR", key: "KR" },
    { label: "Kosovo", value: "XK", key: "XK" },
    { label: "Kuwait", value: "KW", key: "KW" },
    { label: "Kyrgyzstan", value: "KG", key: "KG" },
    { label: "Laos", value: "LA", key: "LA" },
    { label: "Latvia", value: "LV", key: "LV" },
    { label: "Lebanon", value: "LB", key: "LB" },
    { label: "Lesotho", value: "LS", key: "LS" },
    { label: "Liberia", value: "LR", key: "LR" },
    { label: "Libya", value: "LY", key: "LY" },
    { label: "Liechtenstein", value: "LI", key: "LI" },
    { label: "Lithuania", value: "LT", key: "LT" },
    { label: "Luxembourg", value: "LU", key: "LU" },
    { label: "Macao", value: "MO", key: "MO" },
    { label: "North Macedonia", value: "MK", key: "MK" },
    { label: "Madagascar", value: "MG", key: "MG" },
    { label: "Malawi", value: "MW", key: "MW" },
    { label: "Malaysia", value: "MY", key: "MY" },
    { label: "Maldives", value: "MV", key: "MV" },
    { label: "Mali", value: "ML", key: "ML" },
    { label: "Malta", value: "MT", key: "MT" },
    { label: "Marshall Islands", value: "MH", key: "MH" },
    { label: "Martinique", value: "MQ", key: "MQ" },
    { label: "Mauritania", value: "MR", key: "MR" },
    { label: "Mauritius", value: "MU", key: "MU" },
    { label: "Mayotte", value: "YT", key: "YT" },
    { label: "Mexico", value: "MX", key: "MX" },
    { label: "Micronesia", value: "FM", key: "FM" },
    { label: "Moldova", value: "MD", key: "MD" },
    { label: "Monaco", value: "MC", key: "MC" },
    { label: "Mongolia", value: "MN", key: "MN" },
    { label: "Montenegro", value: "ME", key: "ME" },
    { label: "Montserrat", value: "MS", key: "MS" },
    { label: "Morocco", value: "MA", key: "MA" },
    { label: "Mozambique", value: "MZ", key: "MZ" },
    { label: "Myanmar (Burma)", value: "MM", key: "MM" },
    { label: "Namibia", value: "NA", key: "NA" },
    { label: "Nauru", value: "NR", key: "NR" },
    { label: "Nepal", value: "NP", key: "NP" },
    { label: "Netherlands", value: "NL", key: "NL" },
    { label: "Curaçao", value: "AN", key: "AN" },
    { label: "New Caledonia", value: "NC", key: "NC" },
    { label: "New Zealand", value: "NZ", key: "NZ" },
    { label: "Nicaragua", value: "NI", key: "NI" },
    { label: "Niger", value: "NE", key: "NE" },
    { label: "Nigeria", value: "NG", key: "NG" },
    { label: "Niue", value: "NU", key: "NU" },
    { label: "Norfolk Island", value: "NF", key: "NF" },
    { label: "Northern Mariana Islands", value: "MP", key: "MP" },
    { label: "Norway", value: "NO", key: "NO" },
    { label: "Oman", value: "OM", key: "OM" },
    { label: "Pakistan", value: "PK", key: "PK" },
    { label: "Palau", value: "PW", key: "PW" },
    { label: "Palestine", value: "PS", key: "PS" },
    { label: "Panama", value: "PA", key: "PA" },
    { label: "Papua New Guinea", value: "PG", key: "PG" },
    { label: "Paraguay", value: "PY", key: "PY" },
    { label: "Peru", value: "PE", key: "PE" },
    { label: "Philippines", value: "PH", key: "PH" },
    { label: "Pitcairn Islands", value: "PN", key: "PN" },
    { label: "Poland", value: "PL", key: "PL" },
    { label: "Portugal", value: "PT", key: "PT" },
    { label: "Puerto Rico", value: "PR", key: "PR" },
    { label: "Qatar", value: "QA", key: "QA" },
    { label: "Réunion", value: "RE", key: "RE" },
    { label: "Romania", value: "RO", key: "RO" },
    { label: "Russia", value: "RU", key: "RU" },
    { label: "Rwanda", value: "RW", key: "RW" },
    { label: "St. Barthélemy", value: "BL", key: "BL" },
    { label: "St. Helena", value: "SH", key: "SH" },
    { label: "St. Kitts & Nevis", value: "KN", key: "KN" },
    { label: "St. Lucia", value: "LC", key: "LC" },
    { label: "St. Martin", value: "MF", key: "MF" },
    { label: "St. Pierre & Miquelon", value: "PM", key: "PM" },
    { label: "St. Vincent & Grenadines", value: "VC", key: "VC" },
    { label: "Samoa", value: "WS", key: "WS" },
    { label: "San Marino", value: "SM", key: "SM" },
    { label: "São Tomé & Príncipe", value: "ST", key: "ST" },
    { label: "Saudi Arabia", value: "SA", key: "SA" },
    { label: "Senegal", value: "SN", key: "SN" },
    { label: "Serbia", value: "RS", key: "RS" },
    { label: "Serbia", value: "CS", key: "CS" },
    { label: "Seychelles", value: "SC", key: "SC" },
    { label: "Sierra Leone", value: "SL", key: "SL" },
    { label: "Singapore", value: "SG", key: "SG" },
    { label: "Sint Maarten", value: "SX", key: "SX" },
    { label: "Slovakia", value: "SK", key: "SK" },
    { label: "Slovenia", value: "SI", key: "SI" },
    { label: "Solomon Islands", value: "SB", key: "SB" },
    { label: "Somalia", value: "SO", key: "SO" },
    { label: "South Africa", value: "ZA", key: "ZA" },
    { label: "South Georgia & South Sandwich Islands", value: "GS", key: "GS" },
    { label: "South Sudan", value: "SS", key: "SS" },
    { label: "Spain", value: "ES", key: "ES" },
    { label: "Sri Lanka", value: "LK", key: "LK" },
    { label: "Sudan", value: "SD", key: "SD" },
    { label: "Suriname", value: "SR", key: "SR" },
    { label: "Svalbard & Jan Mayen", value: "SJ", key: "SJ" },
    { label: "Eswatini", value: "SZ", key: "SZ" },
    { label: "Sweden", value: "SE", key: "SE" },
    { label: "Switzerland", value: "CH", key: "CH" },
    { label: "Syria", value: "SY", key: "SY" },
    { label: "Taiwan", value: "TW", key: "TW" },
    { label: "Tajikistan", value: "TJ", key: "TJ" },
    { label: "Tanzania", value: "TZ", key: "TZ" },
    { label: "Thailand", value: "TH", key: "TH" },
    { label: "Timor-Leste", value: "TL", key: "TL" },
    { label: "Togo", value: "TG", key: "TG" },
    { label: "Tokelau", value: "TK", key: "TK" },
    { label: "Tonga", value: "TO", key: "TO" },
    { label: "Trinidad & Tobago", value: "TT", key: "TT" },
    { label: "Tunisia", value: "TN", key: "TN" },
    { label: "Turkey", value: "TR", key: "TR" },
    { label: "Turkmenistan", value: "TM", key: "TM" },
    { label: "Turks & Caicos Islands", value: "TC", key: "TC" },
    { label: "Tuvalu", value: "TV", key: "TV" },
    { label: "Uganda", value: "UG", key: "UG" },
    { label: "Ukraine", value: "UA", key: "UA" },
    { label: "United Arab Emirates", value: "AE", key: "AE" },
    { label: "United Kingdom", value: "GB", key: "GB" },
    { label: "United States", value: "US", key: "US" },
    { label: "U.S. Outlying Islands", value: "UM", key: "UM" },
    { label: "Uruguay", value: "UY", key: "UY" },
    { label: "Uzbekistan", value: "UZ", key: "UZ" },
    { label: "Vanuatu", value: "VU", key: "VU" },
    { label: "Venezuela", value: "VE", key: "VE" },
    { label: "Vietnam", value: "VN", key: "VN" },
    { label: "British Virgin Islands", value: "VG", key: "VG" },
    { label: "U.S. Virgin Islands", value: "VI", key: "VI" },
    { label: "Wallis & Futuna", value: "WF", key: "WF" },
    { label: "Western Sahara", value: "EH", key: "EH" },
    { label: "Yemen", value: "YE", key: "YE" },
    { label: "Zambia", value: "ZM", key: "ZM" },
    { label: "Zimbabwe", value: "ZW", key: "ZW" },
];
