name: git tagging

on:
  pull_request:
    branches: 
        - main
    types: [closed]
    
jobs:
  auto-tag:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    permissions: write-all

    # permissions:
    #   packages: write
    #   contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      
      - name: install
        run: npm install
        if: ${{ always() }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_GITHUB_PACKAGES_TOKEN }}

      - name: tag
        run: npm run tag:auto
        if: ${{ always() }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_GITHUB_PACKAGES_TOKEN }}
