name: git tagging

on:
  release:
    types: [released]
    # types: [opened, reopened]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions: 
        packages: write
        contents: read
    steps:
      - run: echo "Publishing package"
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.11.0
          registry-url: https://npm.pkg.github.com/
      
      - name: install
        run: npm ci
        if: ${{ always() }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_GITHUB_PACKAGES_TOKEN }}
        
      - name: build package
        run: npm run build:src

      - name: publish package
        working-directory: ./lib
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_GITHUB_PACKAGES_TOKEN }}
